// Add a line for each repository that needs push access to pypi using its name
// Example: 'limepkg-workorder',
const repositories = [
    'addon-acd',
    'addon-erpconnector',
    'addon-infotiles',
    'addon-lime-event',
    'addon-lime-automation',
    'lime-buildtools',
    'lime-core',
    'lime-crm',
    'lime-dynaconf-consul-loader',
    'lime-integration-tests',
    'lime-imagebaker',
    'lime-newsletter',
    'lime-project',
    'lime-webclient',
    'limepkg-consent',
    'limepkg-credit-info',
    'limepkg-dynamic-checklist',
    'limepkg-engage',
    'limepkg-esign',
    'limepkg-gdpr',
    'limepkg-helpdesk',
    'limepkg-intercom',
    'limepkg-jira-integration',
    'limepkg-merge',
    'limepkg-salesdemo',
    'limepkg-survey-integration',
    'mtech-addon-shared',
    'plugin-real-estate-publishing',
    'transactional-message-library'
]

export default repositories;
